name: CI / Build / Scan

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  static-analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install deps
        run: npm ci

      - name: Run Semgrep (static security)
        uses: returntocorp/semgrep-action@v1
        with:
          config: "p/ci"

  build-and-scan:
    needs: static-analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build image
        run: docker build -t ${{ github.repository }}:${{ github.ref_name }}-${{ github.sha }} .

      - name: Run Trivy image scan
        run: |
          docker run --rm -v /var/run/docker.sock:/var/run/docker.sock aquasec/trivy image --severity CRITICAL,HIGH --exit-code 1 ${{ github.repository }}:${{ github.ref_name }}-${{ github.sha }}

      - name: Push to GHCR (only if scans passed)
        if: success()
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ github.ref_name }}-${{ github.sha }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
