name: CI / Build / Scan

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  static-analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install deps
        run: npm ci

      - name: Run Semgrep (static security)
        uses: returntocorp/semgrep-action@v1
        with:
          config: "p/ci"

  build-and-scan:
    needs: static-analysis
    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/checkout@v4
  
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
  
      - name: Build image
        run: |
          docker build -t docker.io/${{ github.repository }}:${{ github.ref_name }}-${{ github.sha }} .
  
      - name: Install Trivy
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin
  
      - name: Run Trivy image scan
        run: |
          trivy image --severity CRITICAL,HIGH --exit-code 1 docker.io/${{ github.repository }}:${{ github.ref_name }}-${{ github.sha }}

      - name: Push to GHCR (only if scans passed)
        if: success()
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ github.ref_name }}-${{ github.sha }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
